name: inf_cal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.6+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_sign_in: ^6.2.1
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  http: ^1.2.1
  http_client: ^1.5.3
  icalendar_parser: ^2.0.0
  intl: ^0.18.1
  oauth2: ^2.0.2
  path_provider: ^2.1.3
  url_launcher: ^6.2.6
  web: ^0.5.1
  window_to_front: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
